jobs:
  descriptions:
    digger: 'The digger earns money by breaking blocks with the shovel.'
    miner: 'The miner earns money by breaking blocks with the pick axe.'
    builder: 'The builder earns money by placing construction blocks.'
    carpenter: 'The carpenter earns money for crafting wooden and stone objects.'
    soldier: 'A soldier earns cash by clearing the wilderness of monsters.'
    tinkerer: 'Earns money by laying and crafting electrical components.'
    woodsman: 'Earns money by chopping trees and crafting wood items.'
    farmer: 'Slaughtering animals and cultivating crops pays this job.'
    toolmaker: 'Earns money by making stone tools and higher.'
    weaponsmith: 'Earns money by crafting and repairing weaponery.'
    armorer: 'Crafting and repairing armor earns money.'
    fisherman: 'Earn money for catching fish.'
    baker: 'Cooking foods and food based potion items pays the baker.'
    alchemist: 'Crafting defensive potoins pays the alchemist.'
    brewer: 'Brewing offensive potions pays the brewer.'
    enchanter: 'Invoking spells to weapons pays the enchanter.'
    theurgist: 'Enchanting armor objects pays the theurgist.'
    conjurer: 'Applying conjurations to tools pays the conjurer.'
    bulldozer: 'Its expensive to break down the world of minecraft.'
    taxes: 'In this world nothing can be said to be certain, except death and taxes.'
  names:
    digger: 'Digger'
    miner: 'Miner'
    builder: 'Builder'
    carpenter: 'Carpenter'
    soldier: 'Soldier'
    tinkerer: 'tinkerer'
    woodsman: 'Woodsman'
    farmer: 'Farmer'
    toolmaker: 'Toolmaker'
    weaponsmith: 'Weaponsmith'
    armorer: 'Armorer'
    fisherman: 'Fisherman'
    baker: 'Baker'
    alchemist: 'Alchemist'
    brewer: 'Brewer'
    enchanter: 'Enchanter'
    theurgist: 'Theurgist'
    conjurer: 'Conjurer'
    bulldozer: 'Bulldozer'
    taxes: 'Taxes'